import { useEffect, useRef, useState } from 'react';
import { X, Plus, Trash2, Download } from 'lucide-react';
import type { Lighting } from '../hooks/useLighting';
import { DeviceSettings } from '../components/DeviceSettings';
import { AreaCard } from '../components/AreaCard';
import { QuickControl } from '../components/Controls';
import { AlertList, EnergyChart } from '../components/Summary';
export function DetailPanel({page,state,onClose}:{page:string;state:Lighting;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[time,setTime]=useState('18:00'),[mode,setMode]=useState('Tham quan'),[name,setName]=useState(state.displayName),[saved,setSaved]=useState(false);
 const {schedules,setSchedules}=state;
 useEffect(()=>{dialog.current?.showModal();const el=dialog.current;return ()=>el?.close();},[]);
 const download=()=>{const csv='\uFEFFKhu vực,Số đèn,Đang bật\n'+state.areas.map(a=>`${a.name},${a.lamps},${a.on?a.lit:0}`).join('\n')+'\nĐiện năng hôm nay,'+(state.energyKwh??'Chưa có cảm biến')+',kWh\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ATK-bao-cao.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <dialog ref={dialog} className="detail-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="detail-header"><h2>{page.toLocaleUpperCase('vi')}</h2><button aria-label="Đóng" onClick={onClose}><X/></button></div><div className="detail-body">{state.error&&<p role="alert" className="connection-bad">{state.error}</p>}{page==='Khu vực'&&<><p>168 đèn tại 4 khu di tích chính · {state.lit} đèn đang bật</p><div className="area-grid">{state.areas.map(a=><AreaCard key={a.id} area={a} onClick={()=>state.toggleArea(a.id)}/>)}</div><small>Chạm vào khu vực để bật/tắt chiếu sáng. 12 phân khu được nhóm trong 4 khu di tích.</small></>}{page==='Điều khiển'&&<QuickControl state={state}/>} {page==='Cảnh báo'&&<AlertList state={state} all/>}{page==='Giám sát năng lượng'&&<><EnergyChart state={state}/><p>{state.live ? 'Điện năng chỉ hiển thị khi ESP32 có cảm biến đo.' : 'Tiêu thụ hôm nay: 86,4 kWh · Giảm 12% so với hôm qua.'}</p></>}{page==='Báo cáo'&&<><EnergyChart state={state}/><p>Báo cáo hoạt động chiếu sáng · {state.live ? 'Ngõ ra ESP32' : 'Dữ liệu mô phỏng'}</p><button className="gold-button" onClick={download}><Download/> Tải báo cáo CSV</button></>}{page==='Lịch hoạt động'&&<><p>{state.live ? 'Lịch lưu trên ESP32, chạy hằng ngày theo giờ Việt Nam. Mỗi lịch bật các khu vực và áp dụng cảnh đã chọn.' : 'Lịch chiếu sáng mô phỏng; chưa thực thi trên thiết bị.'}</p>{state.live && <label className="schedule-toggle"><input type="checkbox" checked={state.device?.schedulesEnabled??false} onChange={e=>state.setSchedulesEnabled(e.target.checked)}/>Bật lịch tự động trên ESP32</label>}{schedules.map(s=><div className="schedule-row" key={s.id}><strong>{s.time}</strong><span>{s.mode}</span><button aria-label={`Xóa lịch ${s.time}`} onClick={()=>setSchedules(prev=>prev.filter(x=>x.id!==s.id))}><Trash2/></button></div>)}<form onSubmit={e=>{e.preventDefault();setSchedules(prev=>[...prev,{id:Date.now(),time,mode}].sort((a,b)=>a.time.localeCompare(b.time)));}}><label>Thời gian<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>Chế độ<select value={mode} onChange={e=>setMode(e.target.value)}>{['Tham quan','Lễ tưởng niệm','An ninh','Tiết kiệm'].map(m=><option key={m}>{m}</option>)}</select></label><button className="gold-button" type="submit"><Plus/>Thêm lịch</button></form></>}{page==='Cài đặt'&&<form onSubmit={e=>{e.preventDefault();state.changeDisplayName(name);setSaved(true);}}><label>Tên hiển thị<input value={name} required onChange={e=>{setName(e.target.value);setSaved(false);}}/></label><label>Trung tâm<input readOnly value="ATK Định Hóa – Thái Nguyên"/></label><p>{state.live ? 'Đang điều khiển ESP32 qua mạng Wi-Fi.' : 'Chế độ demo · Điều khiển chỉ có hiệu lực trong phiên sử dụng.'}</p><button className="gold-button" type="submit">Lưu cài đặt</button>{saved&&<p role="status">Đã lưu tên hiển thị: {name}</p>}</form>}{page==='Cài đặt'&&<DeviceSettings state={state}/>}</div></dialog>;
}
